trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo "Simulated Maven Build"
    mkdir target
    echo "Demo Build Output" > target/app.war
  displayName: 'Simulate Build Step'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'target'
    ArtifactName: 'simulated-artifact'
    publishLocation: 'Container'


